### ISSUE TITLE
Todo: Support features for Voice in Text

### ISSUE THREAD

**Issue by Erisa** [Erisa/Cliptok#145]
Requirements
- [x] Add "Send messages" override for users when they join VC
- [x] Remove "Send messages" override for users when they leave VC
- [x] (Optional) send a message in VC announcing when someone leaves/joins
- [x] When everybody leaves the VC, purge all messages from it
- [x] Log the purged messages
